[general]
#import = [ "~/.config/alacritty/cyberpunk-neon.toml" ]
live_config_reload = true
working_directory = "None"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Full"
opacity = 0.7
blur = true
startup_mode = "Maximized"
#title = "~"
dynamic_title = true

[font]
size = 13

[env]
#TERM = "xterm-256color"
